### PR TITLE
Status UI issue 92

### LINKED ISSUE #92: UI: add a page to display status of each sample

### PR DESCRIPTION
**Pull request by liz-fw**
draft tab showing sample status table, closes #92

### CODE REVIEW

**Comment by ergz** [comment]
I like it! Can you explore the possibility of color coding the cells based on status? I think at the very least a dim green for those are complete? https://rstudio.github.io/DT/functions.html ..... your call tho if it doesn't look good feel to say nah.

**Review by ergz — CHANGES_REQUESTED** [review]
just explore the color options

**Comment by liz-fw** [comment]
I added a color scheme to the status column and created 3 levels (either a "neutral", a "needs something", or "complete") sort of scale. We can either keep as is (just coloring the status cell) or color the whole row. What do you think?

**Review by ergz — APPROVED** [review]
I like coloring just the single cell, this looks great!

**Pull request merged**
