### PR TITLE
Issue 125 field sheets

### LINKED ISSUE #125: functions for reading in field sheets into database

### PR DESCRIPTION
**Pull request by liz-fw**
closes #125

### CODE REVIEW

**Comment by ergz** [comment]
@liz-fw do you have a spreadsheet I can test with ?

**Comment by liz-fw** [comment]
@ergz good call - this is what i've been using! 
[2024_field_sheets_test_filled.xlsx](https://github.com/SRJPE/grunID/files/13573657/2024_field_sheets_test_filled.xlsx)

**Comment by liz-fw** [comment]
@ergz ready for review ! added the css loader and removed the upload to app message

**Review by ergz — APPROVED** [review]
looks good!

**Pull request merged**
